version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  projbackend:
    build: ./projbackend
    ports:
      - 6200:6200
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 1
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      PORT: 6200
    depends_on:
      - postgres
volumes:
  postgres_data: